"""Change-log watcher engine (§11 #48) — on-demand v1, no live file-watch.

Rides #19's per-agent git attribution: every dashboard agent commits under a
synthetic email on the fixed ``agents.awl-cc-dash.invalid`` domain, so "what
did AI touch" is one pure git query with no maintained ledger::

    git log --author='@agents.awl-cc-dash.invalid'

This module turns that query into a Library document: :func:`refresh` runs the
query in the project cwd (through an injected ``run_git`` callable — the
sidecar binds it to the shared registry bridge's ``git_run`` WSL exec path, so
this module stays hermetically testable), parses the commits, renders a
markdown change log grouped by day, and writes/updates
``<project>/.awl-cc-dash/docs/change-log.md`` via :mod:`library` with
provenance (``created_by="changelog-watcher"``).

The refresh is OPERATOR/AGENT-TRIGGERED only (``POST
/projects/changelog/refresh`` or the product-shipped
``assets/agents/changelog-watcher.md`` agent) — the decided v1 is an on-demand
run; a live file-watch stays deferred (build plan §48 open decision). The doc
is auto-generated and wholesale re-rendered on every refresh — hand edits do
not survive, which the rendered header says out loud.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Callable

import library
import storage
from identity import AGENT_EMAIL_DOMAIN

# The AI-touched author query (§11 #19) — the fixed synthetic-email domain, so
# the log catches the whole fleet regardless of per-agent names.
AUTHOR_QUERY = "@" + AGENT_EMAIL_DOMAIN

# The dashboard-owned change-log document (one per project, under docs/).
DOC_FILENAME = "change-log.md"

# One line per commit, unit-separator (0x1f) delimited so free-text subjects
# and author names can never split a record (git subjects contain no newlines).
_FIELD_SEP = "\x1f"
_LOG_FORMAT = "%h%x1f%an%x1f%ae%x1f%ad%x1f%s"

_PROVENANCE_AUTHOR = "changelog-watcher"


class ChangelogError(Exception):
    """The git enumeration failed (WSL/git error that is not "not a repo")."""


class NotAGitRepoError(ChangelogError):
    """The project cwd is not inside a git repository — honest 400 material."""


def git_log_args() -> list[str]:
    """The git argv (after ``git``) enumerating AI-authored commits.

    Newest-first (git log's native order), ISO-strict dates (so the day
    grouping is a plain prefix cut), and the fixed author query.
    """
    return [
        "log",
        f"--author={AUTHOR_QUERY}",
        "--date=iso-strict",
        f"--pretty=format:{_LOG_FORMAT}",
    ]


def parse_git_log(output: str) -> list[dict[str, str]]:
    """Parse ``git log`` output (in :data:`_LOG_FORMAT`) into commit dicts.

    Returns ``[{sha, author, email, date, subject}]`` in the given (newest-
    first) order. Malformed lines are skipped rather than crashing the refresh
    — an empty output (no AI-authored commits) parses to ``[]``.
    """
    commits: list[dict[str, str]] = []
    for line in (output or "").splitlines():
        parts = line.split(_FIELD_SEP)
        if len(parts) != 5:
            continue
        sha, author, email, date, subject = (p.strip() for p in parts)
        if not sha:
            continue
        commits.append({"sha": sha, "author": author, "email": email,
                        "date": date, "subject": subject})
    return commits


def render_changelog(commits: list[dict[str, str]], *,
                     project_key: str | None = None,
                     generated_at: str | None = None) -> str:
    """Render the change-log markdown: header + day-grouped commit list.

    Commits stay in the given newest-first order; the day heading is the
    ISO-strict date's ``YYYY-MM-DD`` prefix (an unparseable date lands under
    "undated" rather than being dropped). ``generated_at`` is injectable so a
    unit test renders deterministically. Zero commits renders an honest
    "no AI-authored commits" body, never an empty file.
    """
    stamp = generated_at or datetime.now(timezone.utc).strftime(
        "%Y-%m-%dT%H:%M:%SZ")
    lines = [
        "# Change log — AI-authored commits",
        "",
        f"Auto-generated by the change-log watcher (§11 #48) from `git log "
        f"--author='{AUTHOR_QUERY}'` — the per-agent attribution query "
        f"(§11 #19). Do not hand-edit: every refresh re-renders this file "
        f"wholesale. Refresh via `POST /projects/changelog/refresh` or the "
        f"`changelog-watcher` agent.",
        "",
        f"_Last refreshed: {stamp} — {len(commits)} commit(s)"
        + (f" in `{project_key}`" if project_key else "") + "._",
        "",
    ]
    if not commits:
        lines.append("No AI-authored commits found in this repository yet.")
        lines.append("")
        return "\n".join(lines)
    current_day: str | None = None
    for c in commits:
        day = (c.get("date") or "")[:10] or "undated"
        if day != current_day:
            lines.append(f"## {day}")
            lines.append("")
            current_day = day
        lines.append(f"- `{c['sha']}` **{c['author']}** — {c['subject']} "
                     f"(`{c['email']}`)")
    lines.append("")
    return "\n".join(lines)


def refresh(cwd: str, run_git: Callable[[list[str]], dict[str, Any]], *,
            generated_at: str | None = None) -> dict[str, Any]:
    """Enumerate AI-authored commits in ``cwd`` and write/update the doc.

    ``run_git(args) -> {"code", "output"}`` is the injected executor (the
    sidecar binds the registry bridge's ``git_run`` to the project cwd; a unit
    test injects a fake). A first refresh creates the doc via
    :func:`library.create_document`; later refreshes overwrite the same file
    in place (the doc is wholly generated, so a wholesale re-render IS the
    update), and provenance is (re)stamped either way — ``created_at`` sticks
    from the first write by :func:`library.set_provenance`'s contract.

    Returns ``{"filename", "path", "subdir", "commits", "updated"}``.
    Raises :class:`NotAGitRepoError` when ``cwd`` isn't a git repository and
    :class:`ChangelogError` on any other git failure — never a fake success.
    (One nonzero exit that is NOT a failure: an unborn branch — ``git init``
    with zero commits — renders the honest zero-commit log.)
    """
    res = run_git(git_log_args())
    code = res.get("code", -1)
    output = res.get("output") or ""
    if code != 0:
        low = output.lower()
        if code == 128 and "not a git repository" in low:
            raise NotAGitRepoError(
                f"not a git repository: {cwd} — the change log enumerates "
                f"commits, so the project must be a git repo")
        if code == 128 and "does not have any commits yet" in low:
            # A freshly-initialized repo (unborn branch): `git log` exits 128
            # with "your current branch ... does not have any commits yet".
            # That IS the zero-commit state every brand-new project starts in
            # — render the honest empty change log, don't fail the refresh.
            output = ""
        else:
            raise ChangelogError(
                f"git log failed (exit {code}): {output[:300]}")
    commits = parse_git_log(output)
    content = render_changelog(commits,
                               project_key=storage.project_key(cwd),
                               generated_at=generated_at)
    target = storage.ensure_docs_dir(cwd) / DOC_FILENAME
    updated = target.exists()
    if updated:
        # Wholesale re-render of the generated doc (create_document refuses
        # existing targets by design — this update path is deliberate).
        target.write_text(content, encoding="utf-8")
        doc = {"filename": DOC_FILENAME, "path": str(target), "subdir": "docs"}
    else:
        doc = library.create_document(cwd, DOC_FILENAME, content, subdir="docs")
    library.set_provenance(doc["path"], created_by=_PROVENANCE_AUTHOR)
    return {**doc, "commits": len(commits), "updated": updated}
